Datasource collection: "dataSourceQuery" used in "fetch" as well.
The query options were set once and for all during initialization
of the collection, but templates using the Joshfire Factory might
want to send different query options for each "find" request
(typically to force a refresh of the data).

This can now be done through a call to fetch, for instance:
 collection.fetch({
  dataSourceQuery: {
   nocache: true
  },
  success: function () { ... },
  error: function () { ... }
 });